openapi: 3.0.3
info:
  title: Messari Metrics
  description: Service providing metrics on single and aggregate assets from Messari Data.
  version: "1.0"
servers:
- url: http://localhost:8000/api/
paths:
  /aggregate:
    get:
      tags:
      - metrics
      summary: aggregate metrics
      operationId: metrics#aggregate
      parameters:
      - name: tag
        in: query
        allowEmptyValue: true
        schema:
          type: string
          example: Voluptas exercitationem sint sapiente.
        example: Ea voluptate perspiciatis.
      - name: sector
        in: query
        allowEmptyValue: true
        schema:
          type: string
          example: Non eveniet laudantium ipsa.
        example: Non ipsum labore eveniet doloribus.
      responses:
        "200":
          description: OK response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MetricsaggregateResponseBody'
              example:
                aggName: Ea ipsa vitae nesciunt aut ea eos.
                aggValue: Odit deserunt alias deleniti omnis qui.
                chg24hr: 0.5357941098735186
                mktcap: 0.7614869224981689
                price: 0.2827616709063785
                vlm24hr: 0.22824500320696345
  /asset/{slug}:
    get:
      tags:
      - metrics
      summary: asset metrics
      operationId: metrics#asset
      parameters:
      - name: slug
        in: path
        required: true
        schema:
          type: string
          example: Illo pariatur harum amet.
        example: Quam qui nihil vel.
      responses:
        "200":
          description: OK response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MetricsassetResponseBody'
              example:
                assetSlug: Ex rem nihil esse omnis.
                chg24hr: 0.03735890575350507
                mktcap: 0.5894630986407703
                price: 0.5892879747674146
                vlm24hr: 0.9688286091107458
components:
  schemas:
    MetricsaggregateResponseBody:
      $ref: '#/components/schemas/MetricsaggregateResponseBody'
    MetricsassetResponseBody:
      $ref: '#/components/schemas/MetricsassetResponseBody'
