swagger: "2.0"
info:
  title: Messari Metrics
  description: Service providing metrics on single and aggregate assets from Messari Data.
  version: ""
host: localhost:8000
consumes:
- application/json
- application/xml
- application/gob
produces:
- application/json
- application/xml
- application/gob
paths:
  /aggregate:
    get:
      tags:
      - metrics
      summary: aggregate metrics
      operationId: metrics#aggregate
      parameters:
      - name: tags
        in: query
        required: false
        type: string
      - name: sector
        in: query
        required: false
        type: string
      responses:
        "200":
          description: OK response.
          schema:
            $ref: '#/definitions/MetricsAggregateResponseBody'
      schemes:
      - http
  /asset/{slug}:
    get:
      tags:
      - metrics
      summary: asset metrics
      operationId: metrics#asset
      parameters:
      - name: slug
        in: path
        required: true
        type: string
      responses:
        "200":
          description: OK response.
          schema:
            $ref: '#/definitions/MetricsAssetResponseBody'
      schemes:
      - http
definitions:
  MetricsAggregateResponseBody:
    title: MetricsAggregateResponseBody
    type: object
    properties:
      chg24hr:
        type: number
        description: Change in price over last 24 hours
        example: 0.017032677233100632
        format: double
      mktcap:
        type: number
        description: Market cap of asset
        example: 0.8509346921152394
        format: double
      price:
        type: number
        description: Current spot price in USD
        example: 0.6461548232124056
        format: double
      vlm24hr:
        type: number
        description: Volume traded over last 24 hours
        example: 0.713675077241713
        format: double
    example:
      chg24hr: 0.21259636440754803
      mktcap: 0.6755584953023707
      price: 0.7303753751077985
      vlm24hr: 0.45889189017486626
  MetricsAssetResponseBody:
    title: MetricsAssetResponseBody
    type: object
    properties:
      chg24hr:
        type: number
        description: Change in price over last 24 hours
        example: 0.5892879747674146
        format: double
      mktcap:
        type: number
        description: Market cap of asset
        example: 0.9688286091107458
        format: double
      price:
        type: number
        description: Current spot price in USD
        example: 0.6969528185978329
        format: double
      vlm24hr:
        type: number
        description: Volume traded over last 24 hours
        example: 0.48434118404870374
        format: double
    example:
      chg24hr: 0.7237194876627221
      mktcap: 0.4743631451758633
      price: 0.03735890575350507
      vlm24hr: 0.5894630986407703
