swagger: "2.0"
info:
  title: Messari Metrics
  description: Service providing metrics on single and aggregate assets from Messari Data.
  version: ""
host: localhost:8000
consumes:
- application/json
- application/xml
- application/gob
produces:
- application/json
- application/xml
- application/gob
paths:
  /aggregate:
    get:
      tags:
      - metrics
      summary: aggregate metrics
      operationId: metrics#aggregate
      parameters:
      - name: tag
        in: query
        required: false
        type: string
      - name: sector
        in: query
        required: false
        type: string
      responses:
        "200":
          description: OK response.
          schema:
            $ref: '#/definitions/MetricsAggregateResponseBody'
      schemes:
      - http
  /asset/{slug}:
    get:
      tags:
      - metrics
      summary: asset metrics
      operationId: metrics#asset
      parameters:
      - name: slug
        in: path
        required: true
        type: string
      responses:
        "200":
          description: OK response.
          schema:
            $ref: '#/definitions/MetricsAssetResponseBody'
      schemes:
      - http
definitions:
  AggregateMetricsResponseBody:
    title: AggregateMetricsResponseBody
    type: object
    properties:
      aggName:
        type: string
        description: Aggregation name, e.g. tag, sector, etc.
        example: Aut et qui aut fuga rerum.
      aggValue:
        type: string
        description: Aggregation value, e.g. DeFi, FinTech, etc.
        example: Et quasi omnis voluptas.
      chg24hr:
        type: number
        description: Change in price over last 24 hours
        example: 0.11664029684206616
        format: double
      mktcap:
        type: number
        description: Market cap of asset
        example: 0.23486664093182105
        format: double
      price:
        type: number
        description: Current spot price in USD
        example: 0.08459875106494068
        format: double
      vlm24hr:
        type: number
        description: Volume traded over last 24 hours
        example: 0.18722809008973923
        format: double
    example:
      aggName: Voluptatem ipsa architecto perspiciatis dolorem consectetur.
      aggValue: Esse voluptatem aliquid repellat consequuntur temporibus.
      chg24hr: 0.9929941525659658
      mktcap: 0.7683673884901832
      price: 0.9294245883312547
      vlm24hr: 0.4013601690773143
  AssetMetricsResponseBody:
    title: AssetMetricsResponseBody
    type: object
    properties:
      assetSlug:
        type: string
        description: Asset slug
        example: Aut impedit ipsa omnis.
      chg24hr:
        type: number
        description: Change in price over last 24 hours
        example: 0.7527376846536737
        format: double
      mktcap:
        type: number
        description: Market cap of asset
        example: 0.5116974205645489
        format: double
      price:
        type: number
        description: Current spot price in USD
        example: 0.1887322179974729
        format: double
      vlm24hr:
        type: number
        description: Volume traded over last 24 hours
        example: 0.7364241016375906
        format: double
    example:
      assetSlug: Voluptatem dolores ullam.
      chg24hr: 0.6302778024860927
      mktcap: 0.8351616005010166
      price: 0.5812322433580285
      vlm24hr: 0.6308128886420931
  MetricsAggregateResponseBody:
    title: MetricsAggregateResponseBody
    $ref: '#/definitions/AggregateMetricsResponseBody'
  MetricsAssetResponseBody:
    title: MetricsAssetResponseBody
    $ref: '#/definitions/AssetMetricsResponseBody'
